const mock = {
  alerts: [
    {id:'R-1042',place:'Shimla Relief Camp',need:'Drinking Water · 100 L',priority:'CRITICAL',status:'Pending verification'},
    {id:'R-1041',place:'Kandaghat Shelter',need:'First Aid Kits · 24',priority:'HIGH',status:'Volunteer assigned'},
    {id:'R-1038',place:'Solan Community Hall',need:'Dry Ration · 60 kits',priority:'MEDIUM',status:'In transit'}
  ],
  inventory:[['Drinking Water','1,240 L',78],['Dry Ration Kit','340 kits',54],['First Aid Kit','86 kits',32],['Blankets','420 pcs',67]],
  assignments:[['A-204','R-1041','Volunteer 07','ENROUTE','Kandaghat → Shelter'],['A-201','R-1038','Volunteer 03','ACCEPTED','Depot → Solan Hall']]
};

const state = { view:'command', network:navigator.onLine?'online':'offline' };
const view = document.getElementById('view');
const title = document.getElementById('viewTitle');
const eyebrow = document.getElementById('viewEyebrow');
const networkBar = document.getElementById('networkBar');
const networkLabel = document.getElementById('networkLabel');
const networkDetail = document.getElementById('networkDetail');

function esc(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function toast(message){const t=document.getElementById('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000);}
function setNetwork(status,detail){state.network=status;networkBar.className=`network-bar ${status}`;networkLabel.textContent=status.replace('_',' ').toUpperCase();networkDetail.textContent=detail;}

function renderCommand(){return `
<div class="grid metrics"><div class="card"><div class="metric-label">ACTIVE REPORTS</div><div class="metric-value">24</div><div class="metric-note accent-red">5 critical</div></div><div class="card"><div class="metric-label">VOLUNTEERS ONLINE</div><div class="metric-value">18</div><div class="metric-note accent-teal">7 enroute</div></div><div class="card"><div class="metric-label">SHELTER CAPACITY</div><div class="metric-value">78%</div><div class="metric-note">1,842 / 2,360 occupied</div></div><div class="card"><div class="metric-label">DELIVERIES TODAY</div><div class="metric-value">61</div><div class="metric-note accent-blue">92% completed</div></div></div>
<div class="grid split"><div class="card"><div class="section-head"><h2>Live Operations Map</h2><small>Updated 14:32:08</small></div><div class="map"><div class="route r1"></div><div class="route r2"></div><div class="route r3"></div><div class="pin p1 pulse"></div><div class="pin p2"></div><div class="pin p3"></div><div class="map-controls"><button>+</button><button>−</button><button>⌖</button></div></div></div><div class="card"><div class="section-head"><h2>Priority Alert Feed</h2><small>3 new</small></div><div class="alert-list">${mock.alerts.map(a=>`<div class="alert"><div class="alert-top"><strong>${esc(a.id)} · ${esc(a.place)}</strong><span class="tag ${a.priority==='CRITICAL'?'critical':a.priority==='HIGH'?'pending':'active'}">${esc(a.priority)}</span></div><p>${esc(a.need)}<br><span>${esc(a.status)}</span></p></div>`).join('')}</div></div></div>`;}

function renderReport(){return `<div class="report-layout"><div class="card"><div class="section-head"><div><h2>Submit a relief need</h2><small>Only fields accepted by POST /api/reports are sent.</small></div><span class="tag active">API READY</span></div><form id="reportForm"><div class="form-grid"><div class="field"><label for="shelter_id">SHELTER ID · UUID</label><input id="shelter_id" name="shelter_id" required placeholder="e.g. 550e8400-e29b-41d4-a716-446655440000"></div><div class="field"><label for="resource_id">RESOURCE ID · UUID</label><input id="resource_id" name="resource_id" required placeholder="Resource UUID"></div><div class="field"><label for="quantity_needed">QUANTITY NEEDED</label><input id="quantity_needed" name="quantity_needed" type="number" min="1" step="1" required placeholder="100"></div><div class="field"><label for="description">DESCRIPTION</label><input id="description" name="description" required placeholder="Need drinking water urgently"></div><div class="field"><label for="latitude">LATITUDE</label><input id="latitude" name="latitude" type="number" step="any" required placeholder="30.123"></div><div class="field"><label for="longitude">LONGITUDE</label><input id="longitude" name="longitude" type="number" step="any" required placeholder="76.456"></div><div class="field full"><label>LOCATION ASSIST</label><div class="location-row"><button type="button" class="secondary" id="geoBtn">⌖ Use current location</button><input id="latPreview" readonly placeholder="Latitude"><input id="lngPreview" readonly placeholder="Longitude"></div></div></div><div class="actions"><button type="reset" class="secondary">Clear</button><button type="submit" class="primary" id="submitReport">Submit relief request</button></div></form></div></div>`;}

function renderShelter(){return `<div class="grid metrics"><div class="card"><div class="metric-label">OCCUPANCY</div><div class="metric-value">184 / 240</div><div class="progress"><i style="width:77%"></i></div></div><div class="card"><div class="metric-label">OPEN REQUESTS</div><div class="metric-value accent-red">4</div><div class="metric-note">2 critical</div></div><div class="card"><div class="metric-label">INCOMING</div><div class="metric-value accent-teal">2</div><div class="metric-note">deliveries enroute</div></div></div><div class="card"><div class="section-head"><h2>Shelter resource requests</h2><button class="primary" data-view="report">Report need</button></div><table class="table"><thead><tr><th>REPORT</th><th>RESOURCE</th><th>QUANTITY</th><th>STATUS</th></tr></thead><tbody>${mock.alerts.map(a=>`<tr><td>${a.id}</td><td>${a.need.split(' · ')[0]}</td><td>${a.need.split(' · ')[1]}</td><td><span class="tag ${a.priority==='CRITICAL'?'critical':'pending'}">${a.status}</span></td></tr>`).join('')}</tbody></table></div>`;}

function renderReports(){return `<div class="card"><div class="section-head"><h2>Active Reports / Request Tracking</h2><span class="tag pending">${mock.alerts.length} ACTIVE</span></div><table class="table"><thead><tr><th>ID</th><th>SHELTER</th><th>NEED</th><th>PRIORITY</th><th>STATUS</th></tr></thead><tbody>${mock.alerts.map(a=>`<tr><td>${a.id}</td><td>${a.place}</td><td>${a.need}</td><td><span class="tag ${a.priority==='CRITICAL'?'critical':'pending'}">${a.priority}</span></td><td>${a.status}</td></tr>`).join('')}</tbody></table></div>`;}

function renderVolunteer(){return `<div class="grid metrics"><div class="card"><div class="metric-label">MY STATUS</div><div class="metric-value accent-teal">AVAILABLE</div><div class="metric-note">Location sharing active</div></div><div class="card"><div class="metric-label">ACTIVE ASSIGNMENT</div><div class="metric-value">1</div><div class="metric-note">A-204</div></div><div class="card"><div class="metric-label">DELIVERIES</div><div class="metric-value">12</div><div class="metric-note">This operation</div></div></div><div class="card"><div class="section-head"><h2>Route hazard warnings</h2><span class="tag critical">1 BLOCKED ROAD</span></div><div class="alert-list"><div class="alert"><div class="alert-top"><strong>Route A-204 · Ridge Road</strong><span class="tag critical">BLOCKED</span></div><p>Road obstruction reported near waypoint 3. Use the alternate teal route.</p></div><div class="alert"><div class="alert-top"><strong>Assignment A-204</strong><span class="tag active">ENROUTE</span></div><p>Water delivery · 100 L · Kandaghat Shelter</p></div></div></div>`;}

function renderAssignment(){return `<div class="grid split"><div class="card"><div class="section-head"><h2>Assignment A-204</h2><span class="tag active">ENROUTE</span></div><p>Deliver <strong>100 L Drinking Water</strong> to Kandaghat Shelter.</p><div class="map" style="height:300px"><div class="route r1"></div><div class="route r2"></div><div class="pin p1"></div><div class="pin p2"></div></div></div><div class="card"><div class="section-head"><h2>Delivery confirmation</h2><small>Prototype UI</small></div><div class="field"><label>QUANTITY DELIVERED</label><input type="number" value="100"></div><div class="field" style="margin-top:12px"><label>RECIPIENT SIGNATURE</label><div style="height:120px;border:1px dashed #454b54;border-radius:9px;display:grid;place-items:center;color:#6f7781">Signature pad placeholder</div></div><div class="actions"><button class="primary" onclick="toast('Delivery confirmation queued for backend integration')">Confirm delivery</button></div></div></div>`;}

function renderInventory(){return `<div class="card"><div class="section-head"><h2>Inventory Dashboard</h2><span class="tag active">LIVE STOCK</span></div><table class="table"><thead><tr><th>RESOURCE</th><th>AVAILABLE</th><th>LEVEL</th></tr></thead><tbody>${mock.inventory.map(i=>`<tr><td>${i[0]}</td><td>${i[1]}</td><td><div class="progress"><i style="width:${i[2]}%"></i></div></td></tr>`).join('')}</tbody></table></div>`;}

function renderNotifications(){return `<div class="card"><div class="section-head"><h2>Notifications</h2><span class="tag critical">3 UNREAD</span></div><div class="alert-list"><div class="alert"><strong>Critical report received</strong><p>R-1042 requires immediate verification.</p></div><div class="alert"><strong>Road warning</strong><p>Ridge Road is currently blocked. Active assignments should reroute.</p></div><div class="alert"><strong>Inventory threshold</strong><p>First Aid Kits are below the preferred operational buffer.</p></div></div></div>`;}

const screens={command:['LIVE OPERATIONS','Command Center',renderCommand],shelter:['SHELTER OPERATIONS','Shelter Dashboard',renderShelter],report:['EMERGENCY RESPONSE','Emergency Resource Report',renderReport],reports:['REQUEST TRACKING','Active Reports',renderReports],volunteer:['FIELD OPERATIONS','Volunteer Dashboard',renderVolunteer],assignment:['DELIVERY OPERATIONS','Assignment Details',renderAssignment],inventory:['LOGISTICS','Inventory Dashboard',renderInventory],notifications:['OPERATIONS FEED','Notifications',renderNotifications]};

function bind(){document.querySelectorAll('[data-view]').forEach(el=>el.addEventListener('click',()=>navigate(el.dataset.view)));document.getElementById('geoBtn')?.addEventListener('click',getLocation);document.getElementById('reportForm')?.addEventListener('submit',submitReport);}
function navigate(name){state.view=name;const s=screens[name]||screens.command;eyebrow.textContent=s[0];title.textContent=s[1];view.innerHTML=s[2]();document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===name));document.getElementById('sidebar')?.classList.remove('open');bind();}
function getLocation(){if(!navigator.geolocation){toast('Geolocation is not available');return}navigator.geolocation.getCurrentPosition(p=>{document.getElementById('latitude').value=p.coords.latitude.toFixed(6);document.getElementById('longitude').value=p.coords.longitude.toFixed(6);document.getElementById('latPreview').value=p.coords.latitude.toFixed(6);document.getElementById('lngPreview').value=p.coords.longitude.toFixed(6);toast('Location captured')},()=>toast('Location permission unavailable'));}
async function submitReport(event){event.preventDefault();const form=event.currentTarget;const button=document.getElementById('submitReport');const fd=new FormData(form);const payload={shelter_id:String(fd.get('shelter_id')).trim(),resource_id:String(fd.get('resource_id')).trim(),quantity_needed:Number(fd.get('quantity_needed')),description:String(fd.get('description')).trim(),latitude:Number(fd.get('latitude')),longitude:Number(fd.get('longitude'))};if(!Number.isFinite(payload.quantity_needed)||!Number.isFinite(payload.latitude)||!Number.isFinite(payload.longitude)){toast('Check quantity and coordinates');return}button.disabled=true;button.textContent='Submitting…';setNetwork('syncing','Sending report to Flask');try{const result=await API.createReport(payload);setNetwork('synced','Report accepted by backend');toast(result?.data?.id?'Relief request submitted successfully':'Relief request submitted successfully');form.reset()}catch(error){setNetwork(navigator.onLine?'online':'offline',navigator.onLine?'Backend connection available':'Waiting for connectivity');toast(`Submission failed: ${error.message}`)}finally{button.disabled=false;button.textContent='Submit relief request';}}

window.addEventListener('online',()=>setNetwork('online','Connected to ReliefRoute operations'));window.addEventListener('offline',()=>setNetwork('offline','Offline · requests can remain pending sync'));document.getElementById('simulateOffline').addEventListener('click',()=>{setNetwork('offline','Simulated offline state');toast('Offline UI state enabled')});document.getElementById('syncBtn').addEventListener('click',async()=>{setNetwork('syncing','Checking Flask health');try{await API.health();setNetwork('synced','Flask backend is healthy')}catch(_){setNetwork('offline','Backend unavailable')}});document.getElementById('menuBtn').addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'));
navigate('command');
